owner: snipcart
repo: status

sites:
  - name: Merchant Dashboard (app.snipcart.com)
    url: https://app.snipcart.com/
  - name: Snipcart.com
    url: https://snipcart.com/
  - name: Documentation
    url: https://docs.snipcart.com/
  - name: Support Forum
    url: https://support.snipcart.com/

status-website:
  theme: dark
  publish: true
  cname: status.snipcart.com
  logoUrl: https://support.snipcart.com/uploads/default/original/1X/8d5d6eaa88b80a3fbe477637722c750bdb4d0048.png
  name: Snipcart Status Page
