owner: snipcart
repo: status

sites:
  - name: Merchant Dashboard (app.snipcart.com)
    url: https://app.snipcart.com/
  - name: Snipcart.com
    url: https://snipcart.com/
  - name: Documentation
    url: https://docs.snipcart.com/
  - name: Support Forum
    url: https://support.snipcart.com/

status-website:
  publish: true
  cname: status.snipcart.com
  name: Snipcart Status
  logoUrl: https://snipcart.com/favicon-180x180.png
  favicon: https://snipcart.com/favicon-180x180.png
